// Mocks generated by Mockito 5.4.6 from annotations
// in betullarise/test/auto_backup_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:betullarise/services/database_export_import_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseExportImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseExportImportService extends _i1.Mock
    implements _i2.DatabaseExportImportService {
  MockDatabaseExportImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> requestStoragePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestStoragePermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Uint8List?> exportDataAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#exportDataAsBytes, []),
            returnValue: _i3.Future<_i4.Uint8List?>.value(),
          )
          as _i3.Future<_i4.Uint8List?>);

  @override
  _i3.Future<String?> exportData() =>
      (super.noSuchMethod(
            Invocation.method(#exportData, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> importData() =>
      (super.noSuchMethod(
            Invocation.method(#importData, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
