// Mocks generated by hand for RewardsDatabaseHelper
import 'package:betullarise/model/reward.dart';
import 'package:betullarise/database/rewards_database_helper.dart';

// Mock che implementa la stessa interfaccia di RewardsDatabaseHelper (solo getAllRewards)
class MockRewardsDatabaseHelper implements IRewardsDatabaseHelper {
  List<Reward> mockRewards = [];
  bool getAllRewardsCalled = false;

  @override
  Future<List<Reward>> getAllRewards() async {
    getAllRewardsCalled = true;
    return List<Reward>.from(mockRewards);
  }

  // Implementazione dummy per tutti gli altri metodi richiesti da RewardsDatabaseHelper
  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
